- name: Just a simple apt-get update && apt-get upgrade
  hosts: all

  tasks:

  - name: update repo and cache
    apt: 
      update_cache: yes
    

  - name: upgrade apt package
    apt:     
       upgrade: dist 

 
