- name: Just a simple apt-get update && apt-get upgrade
  hosts: all

  tasks:

  - name: update repo and cache
    apt: 
       update: yes
       update_cache: yes 
       cache_valid_time: 3600
    

  - name: upgrade apt package
    apt:     
       upgrade: yes
       update_cache: yes
       cache_valid_time: 3600 

 
