- name: Just a simple apt-get update && apt-get upgrade
  hosts: all
  tasks:

  - name: update repo and cache
    become: yes
    apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
      
  - name: upgrade apt package
    become: yes
    apt: update_cache=yes force_apt_get=yes cache_valid_time=3600 
       
 
